{% set name = "lbdiracwrappers" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/LbDiracWrappers-{{ version }}.tar.gz
  sha256: 98803ca999a7944eb39b5ccbf58d0a807cba33379b37ead6ca6b433c9ad1394d

build:
  entry_points:
    - lb-dirac = LbDiracWrappers:lb_dirac
    - lhcb-proxy-init = LbDiracWrappers:lhcb_proxy_init
    - lhcb-proxy-info = LbDiracWrappers:lhcb_proxy_info
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - lbenv
    - packaging >=20.0

test:
  imports:
    - LbDiracWrappers
  commands:
    - pip check
    - lb-dirac --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/LbDiracWrappers/
  summary: Wrappers for LHCbDirac commands
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
